# Generated by Django 4.0.5 on 2022-06-06 11:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='comments',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='image_caption',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
