# Generated by Django 4.0.5 on 2022-06-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_image_model_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='image',
            field=models.ImageField(default='', upload_to='pictures/'),
        ),
    ]
