# Generated by Django 4.0.5 on 2022-06-06 14:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_model',
            name='comments',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='image_model',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
