# Generated by Django 4.0.5 on 2022-06-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newsletterrecipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_model',
            name='image',
        ),
    ]
