# Generated by Django 4.0.5 on 2022-06-08 07:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_image_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_model',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='post image'),
        ),
    ]
